DROP TABLE IF EXISTS `products`;
CREATE TABLE `products`
(
  `id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `title` VARCHAR(120),
  `genre` CHAR(20) DEFAULT NULL,

  `price` DECIMAL(6,2) NOT NULL,
  `players_min` TINYINT DEFAULT NULL,
  `players_max`  TINYINT DEFAULT NULL,
  `age` TINYINT DEFAULT NULL,
  `image` VARCHAR(100) DEFAULT NULL,
  `description` TEXT,
  `filter` VARCHAR(80) DEFAULT "markdown",
  `recomended` BOOLEAN,
  `sale` BOOLEAN,

  -- MySQL version 5.6 and higher
  `published` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

  -- MySQL version 5.5 and lower
  -- `published` DATETIME DEFAULT NULL,
  -- `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- `updated` DATETIME DEFAULT NULL, --  ON UPDATE CURRENT_TIMESTAMP,

  `deleted` DATETIME DEFAULT NULL
) ENGINE INNODB CHARACTER SET utf8 COLLATE utf8_swedish_ci;
